version: 2

models:
  - name: stg_afg
    columns:
      - name: school_id_giga
        data_tests:
          - unique
          - not_null

      - name: school_id_govt
        data_tests:
          - unique
          - not_null

      - name: school_name
        data_tests:
          - not_null

      - name: latitude
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -90
              max_value: 90
              inclusive: true

      - name: longitude
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -180
              max_value: 180
              inclusive: true

      - name: education_level
        data_tests:
          - accepted_values:
              values:
                - Pre-Primary
                - Primary
                - Secondary
                - Post-Secondary
                - Pre-Primary and Primary
                - Primary and Secondary
                - Pre-Primary, Primary and Secondary
                - Primary, Secondary and Post-Secondary
                - Unknown
