name: ae_de_play
config-version: 2
version: 0.1.0
profile: default

model-paths: [ src/models ]
seed-paths: [ src/seeds ]
test-paths: [ src/tests ]
analysis-paths: [ src/analysis ]
macro-paths: [ src/macros ]

clean-targets:
  - src/target
  - src/dbt_modules
  - src/logs

require-dbt-version: [ '>=1.0.0', '<2.0.0' ]

models:
  ae_de_play:
    materialized: table
    staging:
      materialized: view
      +docs:
        node_color: silver
    +docs:
      node_color: gold

data_tests:
  +store_failures: true
