[tool.poetry]
name = "analytics-data-engg-play"
version = "0.1.0"
description = "Analytics & Data Engineering Playground"
authors = ["Kenneth V. Domingo <hello@kvd.studio>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dagster = "^1.9.10"
dagster-webserver = "^1.9.10"
dbt-core = "^1.8.8"
dagster-dbt = "^0.25.10"
polars = "^1.12.0"
dagster-polars = "^0.25.10"
pyarrow = "^18.0.0"
pydantic = "^2.9.2"
pydantic-settings = "^2.6.1"
dagster-postgres = "^0.25.10"
duckdb = "^1.1.3"
dagster-duckdb-polars = "^0.25.10"
dbt-duckdb = "^1.9.0"
country-converter = "^1.2"
dagster-deltalake = "^0.25.10"
dagster-deltalake-polars = "^0.25.10"
dagster-aws = "^0.25.10"
httpx = "^0.27.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
ipython = "^8.27.0"
sqlfluff = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.dagster]
module_name = "src.definitions"

[tool.ruff]
target-version = "py312"
ignore-init-module-imports = true

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B", "UP"]
ignore = ["E203", "E266", "E501", "E402"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["pydantic.validator"]

[tool.sqlfluff.core]
dialect = "duckdb"
templater = "jinja"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
max_line_length = 88

[tool.sqlfluff.indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[tool.sqlfluff.templater]
unwrap_wrapped_queries = true

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = true

[tool.sqlfluff.templater.dbt]
project_dir = "./"

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"
