version: 2

models:
  - name: cchain__location
    columns:
      - name: adm1_en
      - name: adm1_pcode
      - name: adm2_en
      - name: adm2_pcode
      - name: adm3_en
      - name: adm3_pcode
      - name: adm4_en
      - name: adm4_pcode
      - name: brgy_total_area

  - name: cchain__climate_atmosphere
    columns:
      - name: id
      - name: adm4_pcode
      - name: date
      - name: frequency
      - name: temperature_ave
      - name: temperature_min
      - name: temperature_max
      - name: heat_index
      - name: precipitation
      - name: wind_speed
      - name: relative_humidity
      - name: solar_radiance
      - name: uv_radiance

  - name: cchain__disease_pidsr_totals
    columns:
      - name: id
      - name: frequency
      - name: date
      - name: adm3_pcode
      - name: disease_icd10_code
      - name: disease_common_name
      - name: case_total
