version: 2

models:
  - name: nasa_firms__viirs_stg
    config:
      meta:
        dagster:
          group: nasa_firms
    columns:
      - name: id
      - name: country_id
      - name: latitude
      - name: longitude
      - name: bright_ti4
      - name: bright_ti5
      - name: scan
      - name: track
      - name: acq_date
      - name: acq_time
      - name: satellite
      - name: instrument
      - name: confidence
      - name: version
      - name: frp
      - name: daynight
