version: 2

models:
  - name: afg
    description: School Master data for Afghanistan
    columns:
      - name: school_id_giga
        tests:
          - unique
          - not_null

      - name: school_id_govt
        tests:
          - unique
          - not_null

      - name: school_name
        tests:
          - not_null

      - name: latitude
        tests:
          - not_null

      - name: longitude
        tests:
          - not_null

      - name: education_level
        tests:
          - accepted_values:
              values:
                - Pre-Primary
                - Primary
                - Secondary
                - Post-Secondary
                - Pre-Primary and Primary
                - Primary and Secondary
                - Pre-Primary, Primary and Secondary
                - Primary, Secondary and Post-Secondary
                - Unknown
